name: miem-hse-ml-course
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - wordcloud
